name: Test elixir exercises
on:
  push:
    branches: [develop,main]
  pull_request:
    branches: [develop,main]

env:
  elixir-version: '1.13.1'
  erlang-version: '24.2.0'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - run: |
            cd elixir/hello-world
            export MIX_ENV=test
            mix deps.get
            mix test
