name: Test exercises
on:
  push:
    branches: [develop,main]
  pull_request:
    branches: [develop,main]

env:
  dart-version: '2.15.1'
  elixir-version: '1.13.1'
  erlang-version: '24.2.0'
  ghc-version: '8.10.7'
  node-version: '17.3.0'
  stack-version: '2.7.3'

jobs:
  test-dart:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
        with:
          files: |
            ^dart/
          since_last_remote_commit: 'true'
      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          sdk: ${{ env.dart-version }}
      - name: "Run tests"
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bash javascript-tests.sh
        shell: bash
  test-elixir:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
        with:
          files: |
            ^elixir/
          since_last_remote_commit: 'true'
      - name: "Setup BEAM"
        uses: erlef/setup-beam@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: "Run tests"
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bash elixir-tests.sh
        shell: bash
  test-haskell:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
        with:
          files: |
            ^haskell/
            haskell-tests.sh
          since_last_remote_commit: 'true'
      - name: "Setup GHC"
        uses: haskell/actions/setup@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          ghc-version: ${{ env.ghc-version }}
          enable-stack: true
          stack-version: ${{ env.stack-version }}
      - name: "Run tests"
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bash haskell-tests.sh
        shell: bash
  test-javascript:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
        with:
          files: |
            ^javascript/
          since_last_remote_commit: 'true'
      - name: "Setup Node"
        uses: actions/setup-node@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          node-version: ${{ env.node-version }}
      - name: "Run tests"
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bash javascript-tests.sh
        shell: bash
